version: 0.2
    
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - make install
  post_build:
    commands:
      - make lint
      - make test
      - echo Testing completed on `data`